apiVersion: apps/v1 
kind: Job
metadata:
  name: geopoc-job
spec:
  selector:
    matchLabels:
      app: geopoc
  replicas: 1
  template:
    metadata:
      labels:
        app: geopoc
    spec:
      restartPolicy: Never
      backoffLimit: 1
      containers:
      - name: geopoc
        image: motiuma1/geopoc:BUILDNUM
        env:
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
               name: s3
               key: password
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
               name: postgres
               key: password

